"""Terraform file renderers for GCP Always Free setup.

Each render_*() function returns a string of valid HCL.
All generated files use 2-space indentation (validated in tests).
"""
from __future__ import annotations
import os
import textwrap


def _indent(text: str, spaces: int = 2) -> str:
    return textwrap.indent(text, " " * spaces)


def render_provider(
    project_id: str,
    region: str,
    credentials_file: str | None = None,
    impersonate_sa: str | None = None,
) -> str:
    """Render provider.tf.  Auth pattern selected by what credentials are provided."""
    creds_block = ""
    if credentials_file:
        creds_block = f'\n  credentials = file(var.credentials_file)'
    impersonate_block = ""
    if impersonate_sa:
        impersonate_block = f'\n  impersonate_service_account = var.impersonate_service_account'

    return f"""\
# Generated by cloudbooter-gcp — do not edit manually.
# Re-run setup_gcp_terraform.sh to regenerate.

terraform {{
  required_version = ">= 1.6.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 6.0"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.region{creds_block}{impersonate_block}
}}
"""


def render_variables(
    project_id: str,
    region: str,
    zone: str,
    instance_name: str,
    boot_disk_size_gb: int = 20,
    machine_type: str = "e2-micro",
    include_credentials: bool = False,
    include_impersonation: bool = False,
    include_storage: bool = False,
) -> str:
    """Render variables.tf including all check blocks."""

    storage_vars = ""
    storage_checks = ""
    if include_storage:
        storage_vars = """
variable "storage_region" {
  description = "Cloud Storage bucket region (Always Free: us-east1, us-west1, us-central1)"
  type        = string
  default     = "us-central1"
}

variable "storage_bucket_name" {
  description = "Globally unique Cloud Storage bucket name"
  type        = string
  default     = ""
}
"""
        storage_checks = """
check "storage_region_free_tier" {
  assert {
    condition     = contains(["us-east1", "us-west1", "us-central1"], var.storage_region)
    error_message = "Cloud Storage Always Free requires us-east1, us-west1, or us-central1."
  }
}
"""

    creds_var = ""
    if include_credentials:
        creds_var = """
variable "credentials_file" {
  description = "Path to GCP credentials JSON file (SA key or WIF credential config). Leave empty to use ADC."
  type        = string
  default     = ""
}
"""

    impersonate_var = ""
    if include_impersonation:
        impersonate_var = """
variable "impersonate_service_account" {
  description = "Service account email to impersonate (requires roles/iam.serviceAccountTokenCreator)"
  type        = string
  default     = ""
}
"""

    return f"""\
# Generated by cloudbooter-gcp — do not edit manually.

variable "project_id" {{
  description = "GCP project ID"
  type        = string
  default     = "{project_id}"
}}

variable "region" {{
  description = "GCP region (Always Free compute: us-west1, us-central1, us-east1)"
  type        = string
  default     = "{region}"
}}

variable "zone" {{
  description = "GCP zone within the region"
  type        = string
  default     = "{zone}"
}}

variable "machine_type" {{
  description = "Compute Engine machine type (Always Free: e2-micro)"
  type        = string
  default     = "{machine_type}"
}}

variable "boot_disk_size_gb" {{
  description = "Boot disk size in GB (Always Free cap: 30 GB standard PD)"
  type        = number
  default     = {boot_disk_size_gb}
}}

variable "instance_name" {{
  description = "Name for the Compute Engine instance"
  type        = string
  default     = "{instance_name}"
}}

variable "ssh_public_key" {{
  description = "SSH public key content (injected via instance metadata)"
  type        = string
  default     = ""
}}
{creds_var}{impersonate_var}{storage_vars}
# ── Free-Tier Guard: check blocks ─────────────────────────────────────────────

check "e2_micro_machine_type" {{
  assert {{
    condition     = var.machine_type == "e2-micro"
    error_message = "Only e2-micro is Always Free. Got: ${{var.machine_type}}"
  }}
}}

check "compute_region_free_tier" {{
  assert {{
    condition     = contains(["us-west1", "us-central1", "us-east1"], var.region)
    error_message = "Compute Engine Always Free requires us-west1, us-central1, or us-east1."
  }}
}}

check "standard_pd_limit" {{
  assert {{
    condition     = var.boot_disk_size_gb <= 30
    error_message = "Standard PD Always Free cap is 30 GB."
  }}
}}
{storage_checks}"""


def render_data_sources() -> str:
    """Render data_sources.tf."""
    return """\
# Generated by cloudbooter-gcp — do not edit manually.

data "google_compute_image" "ubuntu" {
  family  = "ubuntu-2404-lts-amd64"
  project = "ubuntu-os-cloud"
}

data "google_project" "current" {}

data "google_compute_zones" "available" {
  region = var.region
}
"""


def render_main(instance_name: str, ssh_user: str = "ubuntu") -> str:
    """Render main.tf — VPC, subnet, firewall × 2, disk, instance."""
    return f"""\
# Generated by cloudbooter-gcp — do not edit manually.

# ── VPC ────────────────────────────────────────────────────────────────────

resource "google_compute_network" "vpc" {{
  name                    = "${{var.instance_name}}-vpc"
  auto_create_subnetworks = false
  description             = "CloudBooter free-tier VPC"
}}

# ── Subnet ─────────────────────────────────────────────────────────────────

resource "google_compute_subnetwork" "subnet" {{
  name          = "${{var.instance_name}}-subnet"
  ip_cidr_range = "10.0.0.0/24"
  region        = var.region
  network       = google_compute_network.vpc.id
}}

# ── Firewall: SSH ───────────────────────────────────────────────────────────

resource "google_compute_firewall" "allow_ssh" {{
  name    = "${{var.instance_name}}-allow-ssh"
  network = google_compute_network.vpc.name

  allow {{
    protocol = "tcp"
    ports    = ["22"]
  }}

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["${{var.instance_name}}"]
  description   = "Allow SSH inbound"
}}

# ── Firewall: ICMP ──────────────────────────────────────────────────────────

resource "google_compute_firewall" "allow_icmp" {{
  name    = "${{var.instance_name}}-allow-icmp"
  network = google_compute_network.vpc.name

  allow {{
    protocol = "icmp"
  }}

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["${{var.instance_name}}"]
  description   = "Allow ICMP (ping)"
}}

# ── Boot Disk ───────────────────────────────────────────────────────────────

resource "google_compute_disk" "boot" {{
  name  = "${{var.instance_name}}-boot"
  type  = "pd-standard"
  zone  = var.zone
  size  = var.boot_disk_size_gb
  image = data.google_compute_image.ubuntu.self_link

  labels = {{
    managed-by = "cloudbooter"
  }}
}}

# ── Instance ────────────────────────────────────────────────────────────────

resource "google_compute_instance" "vm" {{
  name         = var.instance_name
  machine_type = var.machine_type
  zone         = var.zone

  tags = ["${{var.instance_name}}"]

  boot_disk {{
    source      = google_compute_disk.boot.self_link
    auto_delete = false  # Preserve disk on instance destroy
  }}

  network_interface {{
    subnetwork = google_compute_subnetwork.subnet.self_link
    # Ephemeral external IP — free while attached to a running instance
    access_config {{}}
  }}

  metadata = {{
    "ssh-keys"               = "${{"{ssh_user}"}}: ${{var.ssh_public_key}}"
    "enable-oslogin"         = "FALSE"
    "block-project-ssh-keys" = "FALSE"
  }}

  metadata_startup_script = file("${{path.module}}/cloud-init.yaml")

  labels = {{
    managed-by  = "cloudbooter"
    environment = "free-tier"
  }}

  scheduling {{
    preemptible        = false
    automatic_restart  = true
    on_host_maintenance = "MIGRATE"
  }}

  lifecycle {{
    ignore_changes = [metadata_startup_script]
  }}
}}

# ── Outputs ─────────────────────────────────────────────────────────────────

output "instance_external_ip" {{
  description = "External IP of the e2-micro instance"
  value       = google_compute_instance.vm.network_interface[0].access_config[0].nat_ip
}}

output "ssh_command" {{
  description = "SSH command to connect to the instance"
  value       = "ssh {ssh_user}@${{google_compute_instance.vm.network_interface[0].access_config[0].nat_ip}}"
}}

output "console_url" {{
  description = "Google Cloud Console URL for this instance"
  value       = "https://console.cloud.google.com/compute/instancesDetail/zones/${{var.zone}}/instances/${{var.instance_name}}?project=${{var.project_id}}"
}}
"""


def render_cloud_init(hostname: str, extra_packages: list[str] | None = None) -> str:
    """Render cloud-init.yaml compatible with GCE metadata_startup_script."""
    packages = ["curl", "wget", "git", "vim", "htop", "unattended-upgrades"]
    if extra_packages:
        packages.extend(extra_packages)
    pkg_list = "\n".join(f"  - {p}" for p in packages)

    return f"""\
#cloud-config
# Generated by cloudbooter-gcp — compatible with GCE metadata_startup_script

hostname: {hostname}
fqdn: {hostname}.local

package_update: true
package_upgrade: true

packages:
{pkg_list}

write_files:
  - path: /etc/motd
    content: |
      ╔══════════════════════════════════════════════╗
      ║  CloudBooter GCP Free Tier Instance          ║
      ║  Managed by cloudbooter-gcp                  ║
      ╚══════════════════════════════════════════════╝

runcmd:
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades
  - echo "CloudBooter cloud-init complete at $(date)" >> /var/log/cloudbooter-init.log

final_message: "CloudBooter GCP instance {hostname} is ready after $UPTIME seconds"
"""
